- name: Set Prompt
  ansible.builtin.shell: set-prompt grafana

- name: Copy repo file
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repo.s/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed