- name: Set Prompt
  ansible.builtin.shell: set-prompt prometheus

- name: Create Prometheus User
  ansible.builtin.user:
    name: prometheus

- name: Download Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

#- name: Start vault service
#  ansible.builtin.systemd_service:
#    name: vault
#    state: restarted
#    enabled: true